backend: tensorflow
class_name: Sequential
config:
  layers:
  - class_name: Flatten
    config:
      batch_input_shape: !!python/tuple
      - null
      - 8
      - 8
      - 512
      data_format: channels_last
      dtype: float32
      name: flatten_1
      trainable: true
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 100
      use_bias: true
  - class_name: LeakyReLU
    config:
      alpha: 0.30000001192092896
      name: leaky_re_lu_1
      trainable: true
  - class_name: Dropout
    config:
      name: dropout_1
      noise_shape: null
      rate: 0.5
      seed: null
      trainable: true
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 50
      use_bias: true
  - class_name: LeakyReLU
    config:
      alpha: 0.30000001192092896
      name: leaky_re_lu_2
      trainable: true
  - class_name: Dropout
    config:
      name: dropout_2
      noise_shape: null
      rate: 0.3
      seed: null
      trainable: true
  - class_name: Dense
    config:
      activation: softmax
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_3
      trainable: true
      units: 12
      use_bias: true
  name: sequential_1
keras_version: 2.2.4
